apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    networking.knative.dev/visibility: cluster-local
  name: {{ .Chart.Name }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.service.port }}
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: {{ .Values.traffic.percent }}