apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-shop
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-coffeeshop
  project: default
  source:
    path: ./coffee-shop-kustomize/coffee-shop/overlays/production
    repoURL: http://github.com/redhat-gpte-devopsautomation/ocp48_hands_on_apps.git
    targetRevision: HEAD
