apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-shop-pipeline
  namespace: openshift-gitops
spec:
  destination:
    namespace: coffeeshop-pipeline
    server: https://kubernetes.default.svc
  project: coffee-shop
  source:
    path: ./coffee-shop-pipeline
    repoURL: http://github.com/redhat-gpte-devopsautomation/hands_on_apps.git
      #repoURL: http:///OCP_USERNAME-GUID/coffee-shop-final-lab.git
    targetRevision: HEAD

